### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by Ganeshkmoorthy** [shreevatsa/sanskrit#96] opened 2017-05-12 12:16 UTC
I have an issue to report about the results for the following input:
```
योगं योगविदां  शिवं नतिकृतां तन्वन्  श्रितानां मुदा
गेहेसक्तधियां दिशन् विधिहुते स्वकर्मे च योगात्मके
ज्ञानं  चाधिकृतां  द्विजन्मभृत: योग्यं  प्रार्थिनां शंसते
मृत्युर्धावति पञ्चमोक्तिसहितान्  वाक्यं दिशास्मान्  प्रभो
```

The issue is:
Looks like there is a probable bug when reading a sandhyakshara with 3 letters. Here the 2nd line स्वकर्मे the first letter स्व even though is a laghu gets identified as not laghu.

**Comment by shreevatsa** [comment] 2017-05-12 13:58
@Ganeshkmoorthy I know the program has many bugs, but there is no bug here :-)

This is the issue that the recognizer is complaining about:

<img width="439" alt="screen shot 2017-05-12 at 6 46 55 am" src="https://cloud.githubusercontent.com/assets/767530/26000782/196953f8-36df-11e7-9e41-e76c1eba98b6.png">

it's saying that the "sva" syllable there should be replaced with "-", meaning no syllable. (And if you read the line aloud with the "sva", you can sound it out for yourself.) In fact if you click on "Scanning the input" in the "Debugging output" section, you'll find this:

<img width="171" alt="screen shot 2017-05-12 at 6 51 06 am" src="https://cloud.githubusercontent.com/assets/767530/26000886/6771e6fa-36df-11e7-8715-407b8365aae1.png">

The second line has 20 syllables instead of 19.

----

Actually there is another metrical error in the input as intended by the human, which one can see by clicking on the "Reading the input" section:

<img width="774" alt="screen shot 2017-05-12 at 6 53 23 am" src="https://cloud.githubusercontent.com/assets/767530/26000975/b966cdd6-36df-11e7-83f8-381ddf7590df.png">

I think whoever wrote this must have intended द्विजन्मभृतः (ending with visarga), but they typed द्विजन्मभृत: (ending with a colon) because of which this error got missed. With the correct input that would have been identified too:

<img width="706" alt="screen shot 2017-05-12 at 6 55 04 am" src="https://cloud.githubusercontent.com/assets/767530/26001115/177a627a-36e0-11e7-80a8-19a6ebbcecbf.png">

So thank you for this report, I think it shows the importance of having some interactive confirmation in the frontend for as many steps as possible. (E.g. in this case we would have shown "you entered this colon, are you sure it's ok to ignore?" or even suggested "shall I treat it as a visarga instead?" — similarly for other common errors like using s instead of avagraha ऽ and for using short e and o कॆ कॊ instead of long के को).

**Comment by Ganeshkmoorthy** [comment] 2017-05-12 14:08
Shreevatsa,

Thanks for the mail. I have only manually typed the colon. i understand that i should have used the transliteration instead and it uses a different character i believe. But the 2nd line is having only 19 letters isnt it.

regards,
Ganesh K.
--------------------------------------------
On Fri, 5/12/17, Shreevatsa <notifications@github.com> wrote:

 Subject: Re: [shreevatsa/sanskrit] User feedback (#96)
 To: "shreevatsa/sanskrit" <sanskrit@noreply.github.com>
 Cc: "Ganeshkmoorthy" <ganeshkmoorthy@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Friday, May 12, 2017, 1:58 PM
 
 @Ganeshkmoorthy I know
 the program has many bugs, but there is no bug here :-)
 This is the issue that the recognizer is complaining
 about:
 
 it's saying that the "sva" syllable there
 should be replaced with "-", meaning no syllable.
 (And if you read the line aloud with the "sva",
 you can sound it out for yourself.) In fact if you click on
 "Scanning the input" in the "Debugging
 output" section, you'll find this:
 
 The second line has 20 syllables instead of 19.
 
 Actually there is another metrical error in the input as
 intended by the human, which one can see by clicking on the
 "Reading the input" section:
 
 I think whoever wrote this must have intended
 द्विजन्मभृतः (ending with visarga),
 but they typed द्विजन्मभृत: (ending
 with a colon) because of which this error got missed. With
 the correct input that would have been identified too:
 
 So thank you for this report, I think it shows the
 importance of having some interactive confirmation in the
 frontend for as many steps as possible. (E.g. in this case
 we would have shown "you entered this colon, are you
 sure it's ok to ignore?" or even suggested
 "shall I treat it as a visarga instead?" —
 similarly for other common errors like using s instead of
 avagraha ऽ and for using short e and o कॆ कॊ
 instead of long के को).
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by shreevatsa** [comment] 2017-05-12 15:59
Here are the 20 syllables in the line “गेहेसक्तधियां दिशन् विधिहुते स्वकर्मे च योगात्मके”:

1 गे
2 हे
3 स
4 क्त
5 धि
6 यां
7 दि
8 शन् 
9 वि
10 धि
11 हु
12 ते
13 स्व
14 क
15 र्मे
16 च
17 यो
18 गा
19 त्म
20 के

**Comment by shreevatsa** [comment] 2017-05-12 16:10
@Ganeshkmoorthy Forgot to tag your name in the previous comment, so not sure if you will get notified. Trying again:

Here are the 20 syllables in the line “गेहेसक्तधियां दिशन् विधिहुते स्वकर्मे च योगात्मके”:

1 गे
2 हे
3 स
4 क्त
5 धि
6 यां
7 दि
8 शन् 
9 वि
10 धि
11 हु
12 ते
13 स्व
14 क
15 र्मे
16 च
17 यो
18 गा
19 त्म
20 के

If you remove स्व then it has 19 syllables and fits the metre properly.

**Comment by gasyoun** [comment] 2017-05-12 18:21
So no issue.

**Comment by shreevatsa** [comment] 2017-05-20 00:30
@Ganeshkmoorthy I'm closing this report, as there appears to be no bug here. (The line had 20 syllables and so what the tool showed was valid.) Please reopen if you think there is an issue. Regards,

**Closed by shreevatsa** 2017-05-20 00:30 UTC
