### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by vshylaja** [shreevatsa/sanskrit#124] opened 2020-10-25 01:01 UTC
I have an issue to report about the results for the following input:
```
भट्टेर्नष्टो भारविश्चापि नष्टो भिक्षुर्नष्टो भीमसेनोऽपि नष्टः ।
भुक्कुण्डोऽहं भूपतित्स्वं हि राजन् भभापङ्क्तावन्तकः सन्निविष्टः ॥
```

The issue is:
Video doesn't play. (https://www.youtube.com/watch?v=k0c_1eVIWHI)

**Comment by shreevatsa** [comment] 2020-10-25 01:05
It plays fine for me. Note that the "video" it's audio-only, i.e. you can
listen but there's no visual. Is that what you're referring to?

**Comment by vshylaja** [comment] 2020-10-25 03:36
No. It works fine in iPhone. But in a Windows 10 laptop, it doesn't play at all. Video keeps spinning.

**Comment by shreevatsa** [comment] 2020-10-25 04:26
Interesting, thank for the information. On the Windows 10 laptop, 

- Does it play if you visit the video directly? https://www.youtube.com/watch?v=k0c_1eVIWHI

- Does it play if you visit this url? https://www.youtube-nocookie.com/embed/k0c_1eVIWHI?rel=0

**Comment by shreevatsa** [comment] 2023-11-21 14:32
Closing for lack of info. May be specific to that specific laptop or its internet connection or something. Please feel free to reopen if the issue is still happening.

**Closed by shreevatsa** 2023-11-21 14:32 UTC
